added condition to stop and init capture
opentok/opentok-react-native pull request #677
Opened 2023-07-05 14:09 UTC by cnx-caiobarroso

###Description

This PR prevents the *startCapture* and *stopCapture* functions from being called whenever the state isn't the opposite.

### Contributing checklist
- [ x] Code must follow existing styling conventions
- [ x] Added a descriptive commit message
- [ x] Sample apps updated if needed

### Solves issue(s)
https://github.com/opentok/opentok-react-native/issues/676

2023-07-06 22:27 UTC, jeffswartz requested changes
Thanks for the PR @cnx-caiobarroso. Does it need to include changes to the files other than than those in OTScreenCapturer.java? Please remove the unneeded files from the PR.

2023-07-10 13:12 UTC, cnx-caiobarroso commented
@jeffswartz, done!

2023-07-20 17:45 UTC, Panda-ref commented
The original issue clearly claims
`com.opentok.android.Camera2VideoCapturer.stopCapture` crashing.

How does changing `com.opentokreactnative.OTScreenCapturer.stopCapture/startCapture` fix it?

It seems unrelated imo

2023-10-26 19:31 UTC, cnx-caiobarroso commented
@Panda-ref Hmm, I guess you are right, but I can't find this "Camera2VideoCapturer" file. Maybe it's related to the Gradle project?

2023-11-29 13:29 UTC, pietgk commented
Event with it potentially being unrelated, its still an improvement AFAIKT.
So we could merge and finish this PR

2026-02-03 16:01 UTC, closed without merging