Implement new audioFallback API (including publisher audio fallback)
opentok/opentok-react-native pull request #714
Opened 2024-01-25 09:02 UTC by jeffswartz

### Contributing checklist
- [x] Code must follow existing styling conventions
- [x] Added a descriptive commit message
- [x] Sample apps updated if needed

### Solves issue(s)

2024-01-26 21:38 UTC, jintgeorge commented on @types/index.d.ts
> +     * Sent when the publisher stops sending video because of [publisher audio fallback](https://tokbox.com/developer/guides/audio-fallback).
"Sent when the publisher stops sending video because of" seems to be incomplete. Did you mean the link place holder as next word?

2024-01-26 21:42 UTC, jintgeorge commented on CHANGELOG.md
> +# 2.27.0  (January 2023)
2024?

2024-01-26 23:23 UTC, jintgeorge requested changes
Left a minor comment.

2024-01-30 22:05 UTC, jintgeorge approved these changes
LGTM

2024-02-02 17:09 UTC, jvalli approved these changes
+1

2024-02-13 18:09 UTC, merged