End-to-end encryption API enhancement
opentok/opentok-react-native pull request #715
Opened 2024-01-26 01:29 UTC by jeffswartz

### Contributing checklist
- [x] Code must follow existing styling conventions
- [x] Added a descriptive commit message
- [ ] Sample apps updated if needed

### Solves issue(s)

2024-01-29 23:34 UTC, jintgeorge commented on CHANGELOG.md
> +# 2.27.0  (January 2023)
2024?

2024-01-29 23:42 UTC, jintgeorge requested changes
Left a minor comment.

2024-01-30 22:03 UTC, jintgeorge approved these changes
LGTM

2024-02-02 17:17 UTC, jvalli approved these changes
LGTM!

2024-02-13 18:13 UTC, merged